[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev --prefix client"
  targetPort = 5173
  port = 8888
